version: "3.1"

services:
  postgres_database:
    container_name: blu_task_store_postgres
    image: postgres:15.0
    environment:
      POSTGRES_PASSWORD: adminpw
      POSTGRES_USER: admin
      POSTGRES_DB: admindb
    ports:
      - 5432:5432
    networks:
      - blu_task_store_network

  pgadmin:
    container_name: blu_task_store_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpw
    ports:
      - 5050:80
    depends_on:
      - postgres_database
    networks:
      - blu_task_store_network

networks:
 blu_task_store_network:
    driver: bridge
